# docker-compose.yml

version: '3.8'

services:
  app:
    build: .
    container_name: rpn_calculator_app
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: rpn_calculator_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
